### ISSUE TITLE
Moment parse issue

### ISSUE THREAD

**Issue by ljfolino** [dalelotts/angular-date-time-input#12]
When using the control to format input using HH:mm I am getting the wrong date.  The date depending on the input is consistent, but wrong.  An example would be 1503 parses to 12/31/02 19:00.  I have tested the parsing functionality of moment and it parses as expected.  Here is a fiddler that has the moment examples.

https://jsfiddle.net/lfolinowjb/spoqfd7y/2/

**Comment by dalelotts** [comment]
Are you using strict parsing? (the default)  From the example, it looks like you are not using strict mode.  (i.e. 1503 does not match HH:mm!)  Non-strict parsing has very strange behaviors that I am not able to predict.

Also, it seems to me that the input formats are incomplete  - I did not look in detail but I think you need at least these input formats ["hh:mm", "hhmm", "h"]

Closing because this does not seem to be related to this directive, it is a moment issue.
