### ISSUE TITLE
Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function

### ISSUE THREAD

**Issue by nicolasgarnil** [dalelotts/angular-date-time-input#21]
Tried updating from `1.1.0` to `1.2.0` but it only works in development. It breaks the app in the minified version with the following error:

`Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function`

**Comment by dalelotts** [comment]
Strange, since `1.2.0` is intended to fix the issue you describe. Which minifyer are you using?

**Comment by dalelotts** [comment]
Ooops, sorry, thinking about the wrong directive. One minute...

**Comment by nicolasgarnil** [comment]
It's an application generated with Yeoman's [generator-angular](https://github.com/yeoman/generator-angular).

This issue may be related to the fact that the bower snippet mentioned in the README doesn't works as there's no `src/js` directory.  Am I doing something wrong?

I had to change it to:

```json
  "overrides": {
    "angular-date-time-input": {
      "main": [
        "src/dateTimeInput.js",
      ],
      "dependencies": {
        "angular": "^1.x",
        "moment": "^2.x"
      }
    }
  }
```

**Comment by dalelotts** [comment]
That looks okay - thanks for letting me know about the error in the readme. What other libraries are you including?

**Comment by nicolasgarnil** [comment]
Here's my package.json and bower.json: https://gist.github.com/nicolasgarnil/7ce0282ba14e74b7dfe32571a3d8f050

Why does suddenly dateTimeInput.js doesn't contain semicolons? How is this resolved?

**Comment by dalelotts** [comment]
semicolon are not needed in JavaScript except in a few cases - minification parsers will inject semicolons where needed to safely minify this directive - _except in one case_ -  when you concatenate two IIFE's from two separate files into one file before minifying. This code tries to handles that case by starting its IIFE with `;(` rather than just `(`. 

I suspect you have another IIFE coming _after_ this directive that starts only with `(` - in this case you can fix the problem you are having by injecting a `;` between files when concatenating. Including this file last during concatenation would also likely fix the issue. 

Just guessing here since I don't have access to your minification pipeline.  If you need further assistance please give me access to the code or create a minimal working example that recreates the problem.

**Comment by nicolasgarnil** [comment]
That's unfortunate as the error is being thrown in the `vendor.js` file where I don't have control over how the IIFEs start and I'm seeing there are a couple of them which doesn't start with `;`, as for example [daterangerpicker.js](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js) in `bootstrap-daterangepicker`.

I followed your advice and place `dateTimeInput.js` at the end and it worked. But I believe this directive should work right out of the box without needing to inject semicolons or re-arranging the files.

Thanks for your help.

**Comment by dalelotts** [comment]
I can see you might think this problem has something to do with this directive. However, It has nothing to do with this directive.  

You have proven it is not this directive because everything works in development, it only fails when the files are _concatenated and minified_ in a way that causes a JavaScript syntax error. 

The concatenate / minify build chain that you are using does not properly handle the language. Specifically, it does not inject semicolons in the JavaScript code. Fix the build chain and you will never see this problem.  

You don't _have_ to reorder the files. You can also minify then concatenate (leaving a newline between separate files, or you can add a semicolon when concatenating and then minify. You could also use libraries where the author correctly deals with JavaScript ASI by starting IIFE's with `;(` - either way the minified code is the same size.  

I could also terminate the IIFE in this directive with a `;`, but [![JavaScript Style Guide](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)](http://standardjs.com/) will not allow it.

**Comment by dalelotts** [comment]
BTW, you always have control over how the IIFEs start by injecting a `;` between files when you concatenate - this is a one line change for most concatenations.
