### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by noway** [dalelotts/angular-date-time-input#25]
Would be nice if there would be minifed version of the library checked in into the repo, so that it can be required easily from bower and used straight away without the need of minifying it yourself.

**Comment by dalelotts** [comment]
I agree that would be nice and, as I have said in past issues created about checking in minified code (in other projects, not this one), I feel pretty strongly that it's not the right thing to do. 

According to Yahoo, 80% of a Web page’s load time is spent downloading the different pieces-parts of the page: images, stylesheets, scripts, Flash, etc. An HTTP request is made for _each one_ of these elements, so more on-page components (like script tags) means it takes longer for the page to render.

To **_really_** improve page load time, minify and concatenate all of the scripts into one script (preferably with a unique hash), then do the same for the CSS. Also, consider loading common scripts like jquery, angular, etc from CDN's so it's likely the browser will have a cached copy of the script. 

So, since you should (IMO) be minifying your own scripts and concatenating them together, you can include any other script, minified or not, into the same pipeline.  Thus, no need for me to check in a minified version (it's a half measure at best). 

Yes, I know, other projects include minified versions, and I will too... if someone steps up and pays my normal hourly rate to do the initial work and all future maintenance.
