### ISSUE TITLE
Apply input Validations for user.

### ISSUE THREAD

**Issue by mjunaidsalaat** [dalelotts/angular-date-time-input#9]
How do I apply validations for input to not enter any thing else than a proper date format?

**Comment by dalelotts** [comment]
First, this project is a bit out-of-date - as I have time I am updating it to make better use of variouos date formats. 

For now, if moment can parse the input format into a valid date, it is considered valid input. As I get time, I will add the ability to specify the supported date formats - however, this will not restrict input to be one of the supported formats.  

If this directive is not able to parse the input into a valid date, ng-invalid is set and the form is invalid.

ngPattern applies to the model and since the model is a date the pattern will not match.

**Comment by dalelotts** [comment]
Sorry for the extreme delay. Can you verify that the develop branch works as you expect?

**Comment by dalelotts** [comment]
Closing because I believe this is fixed now
